pub const FAMILY: &[&str] = &[
    "Adalgrim",
    "Addlespur",
    "Alderleaf",
    "Bosh",
    "Brightshine",
    "Brushgather",
    "Fishskipper",
    "Goodbarrel",
    "Greenbottle",
    "High-hill",
    "Hightopple",
    "Hilltopple",
    "Leagallow",
    "McRoyne",
    "Scalesweep",
    "Tealeaf",
    "Thorngage",
    "Tosscobble",
    "Underbough",
    "Wanderfoot",
];

pub const FEMALE: &[&str] = &[
    "Amarandine",
    "Andry",
    "Bree",
    "Callie",
    "Cora",
    "Euphemia",
    "Jillian",
    "Kithri",
    "Lavinia",
    "Lidda",
    "Merla",
    "Merrygold",
    "Molley",
    "Nedda",
    "Nib",
    "Qelline",
    "Paela",
    "Portia",
    "Seraphina",
    "Shaena",
    "Silla",
    "Streams",
    "Trym",
    "Vani",
    "Verna",
];

pub const MALE: &[&str] = &[
    "Alton", "Ander", "Cade", "Carp", "Corrin", "Eldon", "Errich", "Finnan", "Garret", "Harkin",
    "Lindal", "Lyle", "Marks", "Merric", "Milo", "Osborn", "Otis", "Patsy", "Perrin", "Pieter",
    "Quinn", "Reed", "Rosco", "Roscoe", "Wellby",
];
