pub(crate) const GOBLIN_STATUS_SYMBOLS: &[&str] = &[
    "Earrings and notches in an ear",
    "Rib bones tied into hair",
    "A belt made from raccoon pelts",
    "A gnome's boot used as a hat",
    "A pouch of toenail clippings from an allied ogre",
    "A frog kept in a jar",
    "Fragile helmets made from axe beak eggs",
    "Nose rings",
    "Painted or stained hands",
    "Bugs kept in a bag for snacking",
    "War cry tatooed on chest",
    "Shields made from ankheg chitin",
    "Bracelet made of pieces of goblins turned into stone",
    "Special breed of rat kept as pet",
    "Teeth pulled out in certain places",
    "Owlbear-feather cloaks",
    "Scars from lashings",
    "Orc-tusk lip piercings",
    "Umbrellas made from dead darkmantles",
    "Cloaks made of scraps from an elven tapestry",
];
