pub(crate) const FEMALE_ABYSSAL: &[&str] = &[
    "Akta",
    "Anakis",
    "Bryseis",
    "Criella",
    "Damaia",
    "Ea",
    "Hania",
    "Incindorita",
    "Kallista",
    "Lerissa",
    "Makaria",
    "Nemeia",
    "Nixoxious",
    "Orianna",
    "Phelaia",
    "Rashaa",
    "Rieta",
    "Talanatha",
    "Zaar",
];

pub(crate) const MALE_ABYSSAL: &[&str] = &[
    "Akmenos", "Amnon", "Barakas", "Damakos", "Ekemon", "Haroun", "Iados", "Ishaq", "Kairon",
    "Leucis", "Melech", "Mordai", "Morthos", "Nizam", "Pelaios", "Skamos", "Therai",
];

pub(crate) const VIRTUE_NAMES: &[&str] = &[
    "Art",
    "Aybtep (\"horned\")",
    "Bahati (\"wise soul\")",
    "Carrion",
    "Chant",
    "Creed",
    "Despair",
    "Devil Dog",
    "Excellence",
    "Fear",
    "Glory",
    "Het (\"smoke\")",
    "Hope",
    "Ideal",
    "Kamen (\"dark\")",
    "Katsu (\"star born\")",
    "Kohl (\"dark eyed\")",
    "Music",
    "Nowhere",
    "Open",
    "Poetry",
    "Quest",
    "Random",
    "Reverence",
    "Sorrow",
    "Temerity",
    "Torment",
    "Weary",
];

pub(crate) const SURNAMES: &[&str] = &["Al-Khem", "Beni-Asmodai", "Zianhur", "Siasobek"];
