pub(crate) const CLAN: &[&str] = &[
    "Balderk",
    "Battlehammer",
    "Brawnanvil",
    "Copperwraught",
    "Dankil",
    "Fireforge",
    "Frostbeard",
    "Grayshard",
    "Gorunn",
    "Hammerwhacker",
    "Holderhek",
    "Ironfist",
    "Ironrune",
    "Loderr",
    "Lutgehr",
    "Rockseeker",
    "Rumnaheim",
    "Strakeln",
    "Torunn",
    "Ungart",
];

pub(crate) const FEMALE: &[&str] = &[
    "Amber",
    "Artin",
    "Audhild",
    "Bardryn",
    "Dagnal",
    "Dazlyn",
    "Diesa",
    "Eldeth",
    "Falkrunn",
    "Finellen",
    "Grizzelda",
    "Gunnloda",
    "Gurdis",
    "Helja",
    "Hlin",
    "Kathra",
    "Kristryd",
    "Ilde",
    "Liftrasa",
    "Mardred",
    "Riswynn",
    "Ruby",
    "Sannl",
    "Torbera",
    "Torgga",
    "Vistra",
];

pub(crate) const MALE: &[&str] = &[
    "Adrik", "Alberich", "Baern", "Barendd", "Brottor", "Bruenor", "Dain", "Darrak", "Delg",
    "Eberk", "Einkil", "Fargrim", "Flint", "Gardain", "Gori", "Gundren", "Harbek", "Kildrak",
    "Morgran", "Norbus", "Nundro", "Orsik", "Oskar", "Rangrim", "Rurik", "Taklinn", "Thardin",
    "Thoradin", "Thorin", "Tordek", "Traubon", "Travok", "Ulfgar", "Veit", "Vondal",
];
