pub(crate) const CHILD: &[&str] = &[
    "Ara", "Bryn", "Del", "Eryn", "Faen", "Innil", "Lael", "Mella", "Naill", "Naeris", "Phann",
    "Rael", "Rinn", "Sai", "Syllin", "Thia", "Vall",
];

pub(crate) const FAMILY: &[&str] = &[
    "Amakiir (Gemflower)",
    "Amastacia (Starflower)",
    "Floshin",
    "Galanodel (Moonwhisper)",
    "Graymantle",
    "Holimion (Diamonddew)",
    "Ilphelkiir (Gemblossom)",
    "Liadon (Silverfrond)",
    "Meliamne (Oakenheel)",
    "Na\u{ef}lo (Nightbreeze)",
    "Siannodel (Moonbrook)",
    "Xiloscient (Goldpetal)",
];

pub(crate) const FEMALE: &[&str] = &[
    "Adrie",
    "Aedyn",
    "Althaea",
    "Anastrianna",
    "Andraste",
    "Antinua",
    "Bethrynna",
    "Birel",
    "Caelynn",
    "Drusilia",
    "Enna",
    "Felosial",
    "Garaele",
    "Ielenia",
    "Iverna",
    "Jelenneth",
    "Keyleth",
    "Leshanna",
    "Lia",
    "Meriele",
    "Mialee",
    "Miraal",
    "Morgwais",
    "Naivara",
    "Ordalf",
    "Quelenna",
    "Quillathe",
    "Sariel",
    "Shanairra",
    "Shava",
    "Silaqui",
    "Theirastra",
    "Thia",
    "Vadania",
    "Valanthe",
    "Vyldara",
    "Xanaphia",
];

pub(crate) const MALE: &[&str] = &[
    "Adran",
    "Aelar",
    "Araithe",
    "Aramil",
    "Arannis",
    "Aust",
    "Beiro",
    "Berrian",
    "Carric",
    "Darfin",
    "Enialis",
    "Erdan",
    "Erevan",
    "Galinndan",
    "Hadarai",
    "Heian",
    "Himo",
    "Immeral",
    "Ivellios",
    "Laucian",
    "Mindartis",
    "Nezznar",
    "Paelias",
    "Peren",
    "Quarion",
    "Riardon",
    "Rolen",
    "Soveliss",
    "Thamior",
    "Tharivol",
    "Theren",
    "Varis",
];
