pub(crate) const CLAN: &[&str] = &[
    "Beren", "Daergel", "Folkor", "Garrick", "Nackle", "Murnig", "Ningel", "Raulnor", "Scheppen",
    "Timbers", "Turen",
];

pub(crate) const FEMALE: &[&str] = &[
    "Bimpnottin",
    "Breena",
    "Caramip",
    "Carlin",
    "Donella",
    "Duvamil",
    "Ella",
    "Ellyjobell",
    "Ellywick",
    "Lilli",
    "Loopmottin",
    "Lorilla",
    "Mardnab",
    "Nissa",
    "Nyx",
    "Oda",
    "Orla",
    "Roywyn",
    "Shamil",
    "Tana",
    "Waywocket",
    "Zanna",
];

pub(crate) const MALE: &[&str] = &[
    "Alston",
    "Alvyn",
    "Boddynock",
    "Brocc",
    "Burgell",
    "Dimble",
    "Eldon",
    "Erky",
    "Fonkin",
    "Frug",
    "Gerbo",
    "Gimble",
    "Glim",
    "Jebeddo",
    "Kellen",
    "Namfoodle",
    "Orryn",
    "Roondar",
    "Seebo",
    "Sindri",
    "Warryn",
    "Wrenn",
    "Zook",
];

pub(crate) const NICKNAMES: &[&str] = &[
    "Aleslosh",
    "Ashhearth",
    "Badger",
    "Cloak",
    "Doublelock",
    "Filchbatter",
    "Fnipper",
    "Ku",
    "Nim",
    "Oneshoe",
    "Pock",
    "Sparklegem",
    "Stumbleduck",
];
