pub(crate) const NAMES: &[&str] = &[
    "Achuak (green)",
    "Aryte (war)",
    "Baeshra (animal)",
    "Darastrix (dragon)",
    "Garurt (axe)",
    "Hissain",
    "Irhtos (secret)",
    "Jhank (hammer)",
    "Kepesk (storm)",
    "Kethend (gem)",
    "Korth (danger)",
    "Kosj (small)",
    "Kothar (demon)",
    "Litrix (armor)",
    "Mirik (song)",
    "Othokent (smart)",
    "Sauriv (eye)",
    "Slosh",
    "Throden (many)",
    "Thurkear (night)",
    "Usk (iron)",
    "Valignat (burn)",
    "Vargach (battle)",
    "Verthica (mountain)",
    "Vutha (black)",
    "Vyth (steel)",
];
