pub(crate) const FEMALE_ABYSSAL: &[&str] = &[
    "Akta",
    "Anakis",
    "Bryseis",
    "Criella",
    "Damaia",
    "Ea",
    "Kallista",
    "Lerissa",
    "Makaria",
    "Nemeia",
    "Nixoxious",
    "Orianna",
    "Phelaia",
    "Rieta",
];

pub(crate) const MALE_ABYSSAL: &[&str] = &[
    "Akmenos", "Amnon", "Barakas", "Damakos", "Ekemon", "Iados", "Kairon", "Leucis", "Melech",
    "Mordai", "Morthos", "Pelaios", "Skamos", "Therai",
];

pub(crate) const VIRTUE_NAMES: &[&str] = &[
    "Art",
    "Carrion",
    "Chant",
    "Creed",
    "Despair",
    "Excellence",
    "Fear",
    "Glory",
    "Hope",
    "Ideal",
    "Music",
    "Nowhere",
    "Open",
    "Poetry",
    "Quest",
    "Random",
    "Reverence",
    "Sorrow",
    "Temerity",
    "Torment",
    "Weary",
];
